### ISSUE TITLE
bug: account page persist after deletion 

### ISSUE THREAD

**Issue by Sednaoui** [candidelabs/candide-mobile-app#78]
Account Page persist even after being removed, if being deleted and user is on selected account. 

How to replicate: 
- create a goerli account & optimism-goerli account. 
- Go to goerli account
- Remove goerli account from settings
- Account removed from list, but still visible as the selected account

Expected behavior: Navigate to the next account

**Comment by andrewwahid** [comment]
fixed in 5979a046e64059e503b7f0b8b24a25286d1d127a
