### ISSUE TITLE
bug: nickname prompt is asked twice

### ISSUE THREAD

**Issue by Sednaoui** [candidelabs/candide-mobile-app#79]
When creating a new account, nickname prompt is asked twice. Happens on recovery

**Comment by Naveenchand06** [comment]
Hi, @Sednaoui I would like to work on this issue.

**Comment by Sednaoui** [comment]
@Naveenchand06 thanks for suggesting to work on this issue. This one got recently resolved, forgot to close it. 

There's a few others that are still open and that have good first issue  #98 #93 and #36
