### ISSUE TITLE
UI - small interface glitches

### ISSUE THREAD

**Issue by stefan-b10** [candidelabs/candide-mobile-app#89]
![photo_2023-05-02_11-01-44](https://user-images.githubusercontent.com/72396423/235613881-8b91cf6f-4267-4267-add4-33dee298b277.jpg)

**Comment by stefan-b10** [comment]
Getting this screen when trying to swap 0.0000001 (any token) 
![photo_2023-05-02_11-01-44](https://user-images.githubusercontent.com/72396423/235622169-34aabc8c-6fe2-49c1-9690-551fd764a2cc.jpg)

**Comment by andrewwahid** [comment]
fixed in b3e7a6cc37d53f916a423acdce634ada01e90b4c and 91c889a500f6711389245d05a3acd7cc1f8ca40c, thanks for the feedback
